export const shopData = [
  {
    id: 1,
    title: "NonStick Grys Cookware Set",
    price: "23.00",
    rating: "5",
    newRating: "5 Star",
    newPrice: "UNDER 100",
    category: "Cookware",
    img: "https://ciyashop.potenzaglobalsolutions.com/cookware/wp-content/uploads/sites/90/2018/01/product-1-2-500x600.jpg",
  },
  {
    id: 2,
    title: "Kitchen Tool",
    price: "39.00",
    rating: "4",
    newRating: "4 Star",
    newPrice: "UNDER 100",
    category: "Kitchen Tool",
    img: "https://ciyashop.potenzaglobalsolutions.com/cookware/wp-content/uploads/sites/90/2018/01/product-9-500x600.jpg",
  },
  {
    id: 3,
    title: "Kitchen Tool Box",
    price: "120.00",
    rating: "3",
    newRating: "3 Star",
    newPrice: "100 : 200",
    category: "Kitchen Tool",
    img: "https://ciyashop.potenzaglobalsolutions.com/cookware/wp-content/uploads/sites/90/2018/01/product-5-500x600.jpg",
  },
  {
    id: 4,
    title: "Tea Towels",
    price: "26.00",
    rating: "2",
    newRating: "2 Star",
    newPrice: "UNDER 100",
    category: "Kitchen Tool",
    img: "https://ciyashop.potenzaglobalsolutions.com/cookware/wp-content/uploads/sites/90/2018/01/product-7-500x600.jpg",
  },
  {
    id: 5,
    title: "Knife Kitchen Knives",
    price: "18.00",
    rating: "1",
    newRating: "1 Star",
    newPrice: "UNDER 100",
    category: "Knife",
    img: "https://ciyashop.potenzaglobalsolutions.com/cookware/wp-content/uploads/sites/90/2018/01/product-3-2-500x600.jpg",
  },
  {
    id: 6,
    title: "Aluminium Pressure Cooker",
    price: "110.00",
    rating: "5",
    newRating: "5 Star",
    newPrice: "100 : 200",
    category: "Pressure Cooker",
    img: "https://ciyashop.potenzaglobalsolutions.com/cookware/wp-content/uploads/sites/90/2018/01/product-4-500x600.jpg",
  },
  {
    id: 7,
    title: "Blender Smoothie Mixer",
    price: "130.00",
    rating: "4",
    newRating: "4 Star",
    newPrice: "100 : 200",
    category: "Smoothie Mixer",
    img: "https://ciyashop.potenzaglobalsolutions.com/cookware/wp-content/uploads/sites/90/2018/01/product-6-2-500x600.jpg",
  },
  {
    id: 8,
    title: "Fork and Spoon",
    price: "210.00",
    rating: "3",
    newRating: "3 Star",
    newPrice: "200 : 300",
    category: "Spoon",
    img: "https://ciyashop.potenzaglobalsolutions.com/cookware/wp-content/uploads/sites/90/2018/01/product-10-500x600.jpg",
  },
  {
    id: 9,
    title: "Grater Stainless Steel",
    price: "32.00",
    rating: "5",
    newRating: "5 Star",
    newPrice: "UNDER 100",
    category: "Stainless Steel",
    img: "https://ciyashop.potenzaglobalsolutions.com/cookware/wp-content/uploads/sites/90/2018/01/product-2-500x600.jpg",
  },
  {
    id: 10,
    title: "Tea Cup Set",
    price: "340.00",
    rating: "3",
    newRating: "3 Star",
    newPrice: "300 : 400",
    category: "Tea Cup",
    img: "https://ciyashop.potenzaglobalsolutions.com/cookware/wp-content/uploads/sites/90/2018/01/product-8-500x600.jpg",
  },
  {
    id: 11,
    title: "Teapot Pressure",
    price: "410.00",
    rating: "2",
    newRating: "2 Star",
    newPrice: "400 : 500",
    category: "Teapot Pressure",
    img: "https://ciyashop.potenzaglobalsolutions.com/cookware/wp-content/uploads/sites/90/2018/01/product-11-500x600.jpg",
  },
  {
    id: 12,
    title: "Kitchen Tool Box",
    price: "520.00",
    rating: "3",
    newRating: "3 Star",
    newPrice: "ABOVE 500",
    category: "Kitchen Tool",
    img: "https://ciyashop.potenzaglobalsolutions.com/cookware/wp-content/uploads/sites/90/2018/01/product-5-500x600.jpg",
  },
];

export const productsData = [
  {
    id: 1,
    img: "https://ciyashop.potenzaglobalsolutions.com/cookware/wp-content/uploads/sites/90/2018/01/product-1-2-500x600.jpg",
    title: "Cookware",
    category: "NonStick Grys Cookware Set",
    price: "19.00",
    desc: "Elevate your cat’s meals to the next level by offering her a heaping bowl of Purina Fancy Feast Classic Chicken Feast wet cat food.",
  },
  {
    id: 2,
    img: "https://ciyashop.potenzaglobalsolutions.com/cookware/wp-content/uploads/sites/90/2018/01/product-2-500x600.jpg",
    title: "Stainless Steel",
    category: "Grater Stainless Steel",
    price: "22.00",
    desc: "Time is precious and goes by quicker than you expect. Quit wasting time shopping and purchase an order of Purina Fancy Feast Broths Classic with Shrimp & Whitefish.",
  },
  {
    id: 3,
    img: "https://ciyashop.potenzaglobalsolutions.com/cookware/wp-content/uploads/sites/90/2018/01/product-3-2-500x600.jpg",
    title: "Knife",
    category: "Knife Kitchen Knives",
    price: "18.00",
    desc: "Give your dog Purina® Busy® Bone small/medium adult dog chew treats, and watch him get swept up in the long-lasting fun.",
  },
  {
    id: 4,
    img: "https://ciyashop.potenzaglobalsolutions.com/cookware/wp-content/uploads/sites/90/2018/01/product-4-500x600.jpg",
    title: "Pressure Cooker",
    category: "Aluminium Pressure Cooker",
    price: "19.00",
    desc: "Lifebuoy Total 10 Germ Protection Hand Wash contains our patented ingredient, Activ Naturol Shield, ensuring your hands are clean and protected against germs.",
  },
  {
    id: 5,
    img: "https://ciyashop.potenzaglobalsolutions.com/cookware/wp-content/uploads/sites/90/2018/01/product-5-500x600.jpg",
    title: "Kitchen Tool",
    category: "Kitchen Tool Box",
    price: "21.00",
    desc: "Revital H Capsule is a daily dose of nutrients and daily health supplement with an appropriate concentration of nutrients required for a man to stay fit and healthy.",
  },
  {
    id: 6,
    img: "https://ciyashop.potenzaglobalsolutions.com/cookware/wp-content/uploads/sites/90/2018/01/product-6-2-500x600.jpg",
    title: "Smoothie Mixer",
    category: "Blender Smoothie Mixer",
    price: "66.00",
    desc: "Optimum Nutrition Tablet is a comprehensive Nutrient Optimization System providing 75+ active ingredients each serving includes a free form of amino acids.",
  },
  {
    id: 7,
    img: "https://ciyashop.potenzaglobalsolutions.com/cookware/wp-content/uploads/sites/90/2018/01/product-7-500x600.jpg",
    title: "Kitchen Tool",
    category: "Tea Towels",
    price: "26.00",
    desc: "Fish oil Softgel Capsules contains Fish oil. Fish Oils contain long-chain fatty acids, including docosahexaenoic acid (DHA) and Eicosapentaenoic acid (EPA).",
  },
  {
    id: 8,
    img: "https://ciyashop.potenzaglobalsolutions.com/cookware/wp-content/uploads/sites/90/2018/01/product-8-500x600.jpg",
    title: "Tea Cup",
    category: "Tea Cup Set",
    price: "45.00",
    desc: "Pregnant or lactating women and people with any medical condition should consult physician before consuming any health product.",
  },
];

export const blogData = [
  {
    id: 1,
    img: "https://ciyashop.potenzaglobalsolutions.com/cookware/wp-content/uploads/sites/90/2017/08/blog-img1-1200x600.jpg",
    date: "AUGUST 14, 2017",
    title: "Blog Post With Image",
    desc: "I truly believe Augustine’s words are true and if you look at history you know it is true. There are many people in the world with amazing talents who realize only a small percentage of their potential. We all know people who live this truth. we also know those epic stories, those modern-day legends surrounding […]",
  },
  {
    id: 2,
    img: "https://ciyashop.potenzaglobalsolutions.com/cookware/wp-content/uploads/sites/90/2017/08/blog-img6-1200x600.jpg",
    date: "AUGUST 14, 2017",
    title: "Blog Post With Image Slider",
    desc: "Success isn’t really that difficult. there is a significant portion of the population here in North America, that actually want and need success to be hard! Why? so they then have a built-in excuse when things don’t go their way! pretty sad situation, to say the least. for those of you who are serious about […]",
  },
  {
    id: 3,
    img: "https://ciyashop.potenzaglobalsolutions.com/cookware/wp-content/uploads/sites/90/2017/08/blog-img2-1200x600.jpg",
    date: "AUGUST 14, 2017",
    title: "Blog Post With Image Slider",
    desc: "Success isn’t really that difficult. there is a significant portion of the population here in North America, that actually want and need success to be hard! Why? so they then have a built-in excuse when things don’t go their way! pretty sad situation, to say the least. for those of you who are serious about […]",
  },
];
